# The key used in creating the HMAC hash that must be sent in the Zeek-HMAC header when
# making requests to benchmark remote builds.
HMAC_KEY: unset

# URL prefixes  we allow fetching build artifacts from
ALLOWED_BUILD_URLS:
  - https://api.cirrus-ci.com/v1/artifact/build
  - https://api.cirrus-ci.com/v1/artifact/task
  - http://127.0.0.1:8000/
  - http://localhost:8000/
  - http://test-http:8000/

# Filename of a pcap file used by the zeek endpoint. This should be stored in the path
# referred to by the test_data docker volume.
DATA_FILE: unset

# Path to a cluster-config data file used by the broker endpoint. This should be
# stored in the path referred to by the broker_test_data docker volume.
BROKER_CONFIG_FILE_NAME: unset

# Path to an sqlite database file that stores the metrics once they're completed for
# viewing on grafana, etc.
DATABASE_FILE: ./persistent/unset

# Can be absolute or relative.
WORK_DIR: ./spool


# Set of two CPUs to be used by the zeek endpoint.
CPU_SET:
  - 1
  - 2

# Default number of times each test runs. Can be overridden by providing
# a runs key within each test.
RUN_COUNT: 1

# Max time for unpacking the build archives.
TAR_TIMEOUT: 20

# Path to a YAML file describing which tests to run.
TESTS_FILE: ./config-tests.yml

rq:
  logging:
    dict_config:
      version: 1
      disable_existing_loggers: false
      formatters:
        standard:
          format": "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
      handlers:
        default:
          formatter: "standard"
          class: "logging.StreamHandler"
          stream: "ext://sys.stderr"  # Default is stderr
        smtp:
          formatter: "standard"
          class: "zeek_benchmarker.logging.SMTPHandler"
          level: "ERROR"
          subject_prefix: "zeek-benchmarker"
          toaddrs:
            - arne.welzel@corelight.com
      loggers:
        root:
          handlers: ["default", "smtp"]
          level: "INFO"

        zeek_benchmarker.tasks:
          level: "DEBUG"
          propagate: true


# SMTP settings used for email.
smtp:
  credentials:
    username: unset
    password: unset
  host: email-smtp.us-east-1.amazonaws.com
  port: 587
  fromaddr: zeek-benchmarker@zeek.org
